#ifndef BASE_H
#define BASE_H

enum analysis_t { POG, SS, HAD, STOP, ZMET, WW };
enum id_level_t { 
  //SS
  SS_veto_noiso_v1, 
  SS_veto_v1, 
  SS_fo_noiso_v1, 
  SS_fo_v1, 
  SS_medium_noiso_v1, 
  SS_medium_v1, 
  SS_tight_noiso_v1, 
  SS_tight_v1, 
  SS_veto_noiso_v2, 
  SS_veto_v2, 
  SS_fo_noiso_v2, 
  SS_fo_v2, 
  SS_medium_noiso_v2, 
  SS_medium_v2, 
  SS_tight_noiso_v2, 
  SS_tight_v2, 
  SS_veto_noiso_v3, 
  SS_veto_v3, 
  SS_veto_noiso_noip_v3,
  SS_fo_looseMVA_noiso_noip_v3,
  SS_medium_looseMVA_noip_v3,
  SS_medium_noip_v3,
  SS_fo_noiso_noip_v3,
  SS_fo_noiso_v3, 
  SS_fo_v3, 
  SS_fo_looseMVA_noiso_v3, 
  SS_fo_looseMVA_v3, 
  SS_medium_noiso_v3, 
  SS_medium_v3, 
  SS_tight_noiso_v3, 
  SS_tight_v3, 
  SS_medium_noiso_v4,
  SS_medium_v4,
  SS_medium_looseMVA_noip_v4,
  SS_medium_noip_v4,
  SS_tight_noiso_v4,
  SS_tight_v4,

  //MT2
  HAD_veto_noiso_v1,
  HAD_veto_v1, 
  HAD_loose_noiso_v1, 
  HAD_loose_v1, 
  HAD_medium_noiso_v1, 
  HAD_medium_v1, 
  HAD_tight_noiso_v1, 
  HAD_tight_v1, 
  HAD_veto_noiso_v2,
  HAD_veto_v2, 
  HAD_loose_noiso_v2, 
  HAD_loose_v2, 
  HAD_medium_noiso_v2, 
  HAD_medium_v2, 
  HAD_tight_noiso_v2, 
  HAD_tight_v2, 
  HAD_veto_noiso_v3,
  HAD_veto_v3, 
  HAD_loose_noiso_v3, 
  HAD_loose_v3, 
  HAD_medium_noiso_v3, 
  HAD_medium_v3, 
  HAD_tight_noiso_v3, 
  HAD_tight_v3,

  //Stop
  STOP_veto_v1, 
  STOP_loose_v1, 
  STOP_medium_v1, 
  STOP_tight_v1,
  STOP_sync_v1,
  STOP_veto_v2,
  STOP_loose_v2,
  STOP_medium_v2,
  STOP_tight_v2,

  //Z+MET
  ZMET_mediumMu_v1, 
  ZMET_mediumMu_noiso_v1, 
  ZMET_tightMVA_v1, 
  ZMET_tightMVA_noiso_v1, 
  ZMET_loose_v1, 
  ZMET_loose_noiso_v1, 
  ZMET_loose_v2, 
  ZMET_loose_noiso_v2,
  ZMET_tight_v1, 
  ZMET_tight_noiso_v1, 
  ZMET_tight_v2, 
  ZMET_tight_noiso_v2, 
  ZMET_photon_v2,
  ZMET_photon_v1,

  //WW
  WW_veto_noiso_v1, 
  WW_veto_v1, 
  WW_veto_noiso_noip_v1,
  WW_fo_looseMVA_noiso_noip_v1,
  WW_medium_looseMVA_noip_v1,
  WW_medium_noip_v1,
  WW_fo_noiso_noip_v1,
  WW_fo_noiso_v1, 
  WW_fo_v1, 
  WW_fo_looseMVA_noiso_v1, 
  WW_fo_looseMVA_v1, 
  WW_medium_noiso_v1, 
  WW_medium_v1, 
  WW_tight_noiso_v1, 
  WW_tight_v1,
  WW_veto_noiso_v2, 
  WW_veto_v2, 
  WW_fo_noiso_v2, 
  WW_fo_v2, 
  WW_medium_noiso_v2, 
  WW_medium_v2

};

analysis_t whichAnalysis(id_level_t id_level);

#endif
